# Generated by Django 4.2.1 on 2023-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country_Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=1000)),
                ("country_code", models.CharField(max_length=1000)),
                ("dial_code", models.CharField(max_length=1000)),
                ("flag", models.URLField(max_length=1000)),
            ],
            options={
                "ordering": ["country_name"],
            },
        ),
    ]
