# Generated by Django 4.2.1 on 2023-05-06 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country_code",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="country_code",
            old_name="country_code",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="country_code",
            old_name="country_name",
            new_name="short_name",
        ),
    ]
